## base yml file for all services for prod profile in the config service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
## Actuator related configurations
management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh

  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      default:
        contentType: application/json
        group: ${spring.application.name}-group

info:
  app:
    name: ${spring.application.name}
    description: Vet-Links ${spring.application.name} Management Service Prod
    version: 1.0.0



