## base yml file for all services for local profile in the config service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
## Actuator related configurations
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
      default:
        contentType: application/json
        group: ${spring.application.name}-group

info:
  app:
    name: ${spring.application.name}
    description: Vet-Links ${spring.application.name} Management Service Local Profile
    version: 1.0.0








