spring:
  cloud:
    function:
      definition: >
        userRegistrationComplete;
        deleteUserComplete;
        appointmentBookedComplete;
        appointmentStatusChanged
    stream:
      bindings:
        userRegistrationComplete-in-0:
          destination: create-user-complete
        deleteUserComplete-in-0:
          destination: delete-user-complete
        appointmentBookedComplete-in-0:
          destination: appointment-booked-complete
        appointmentStatusChanged-in-0:
          destination: appointment-status-changed
  mail:
    host: smtp.gmail.com
    port: 587
    username: petuniversal8@gmail.com
    password: ${EMAIL_PASSWORD} # externalized for security
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

frontend:
  base:
    url: "http://frontend:5174"
